# go-arch-lint configuration for Hexagonal/Onion Architecture
# Configured for jira-sync project structure
#
# Install: go install github.com/fe3dback/go-arch-lint@latest
# Usage:   go-arch-lint check
# Graph:   go-arch-lint graph

version: 3
workdir: internal

# Allow all vendor imports (we only enforce component boundaries)
allow:
  depOnAnyVendor: true

# Define architectural components
components:
  # OUTER LAYER: Adapters (Infrastructure implementations)
  filesystem:
    in: adapters/filesystem/**

  jira:
    in: adapters/jira/**

  hashing:
    in: adapters/hashing/**

  # APPLICATION LAYER: Services/Use Cases
  pull:
    in: application/pull/**

  push:
    in: application/push/**

  export:
    in: application/export/**

  transition:
    in: application/transition/**

  # INNER LAYERS: Core Business Logic
  ports:
    in: ports/**

  domain:
    in: domain/**

  # Supporting
  config:
    in: config/**

  # Integration tests (separate component)
  integration:
    in: integration/**

# Components that can be used by all other components
commonComponents:
  - domain
  - ports

# Dependency rules - defines allowed import relationships
deps:
  # Application services implement business logic using ports
  pull:
    mayDependOn:
      - ports

  push:
    mayDependOn:
      - ports

  export:
    mayDependOn:
      - ports

  transition:
    mayDependOn:
      - ports

  # Ports define interfaces - only depend on domain types (via commonComponents)
  ports:
    anyVendorDeps: true

  # Domain is pure - NO external dependencies (innermost layer)
  domain:
    anyVendorDeps: true

  # Filesystem adapter implements TaskRepository port
  filesystem:
    mayDependOn:
      - ports

  # Jira adapter implements JiraClient port
  jira:
    mayDependOn:
      - ports

  # Hashing adapter implements HashComputer port
  hashing:
    mayDependOn:
      - ports

  # Config is standalone
  config:
    anyVendorDeps: true

  # Integration tests can use everything
  integration:
    anyProjectDeps: true

# Exclude test files from analysis
excludeFiles:
  - _test\.go$
  - mock_.*\.go$
  - /mocks/
  - /testdata/
