version: "3"

# Built-in variables used: OS, ARCH, ROOT_DIR
output: prefixed

vars:
  BINARY:
    sh: basename -s .git $(git remote get-url origin)

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - mkdir -p {{.ROOT_DIR}}/bin/{{.OS}}-{{.ARCH}}
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build -o {{.ROOT_DIR}}/bin/{{.OS}}-{{.ARCH}}/{{.BINARY}}
      - chmod +x {{.ROOT_DIR}}/bin/{{.OS}}-{{.ARCH}}/{{.BINARY}}

  run:
    desc: Run the binary
    cmds:
      - "{{.ROOT_DIR}}/bin/{{.OS}}-{{.ARCH}}/{{.BINARY}}"

  clean:
    desc: Clean /bin directory
    cmds:
      - rm -rf {{.ROOT_DIR}}/bin

  install:
    desc: Install the binary using go install
    cmds:
      - GOOS={{.OS}} GOARCH={{.ARCH}} go install

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run -v -c {{.ROOT_DIR}}/.golangci.yml

  test:
    desc: Run go tests
    cmds:
      - go test ./...

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...
